networks:
  registry:
    driver: bridge
services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8083:8083"
    networks:
      - registry
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
  redis:
    image: "redis:4.0-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - registry
  mongodb:
    image: "mongo:3.4.10"
    container_name: mongodb
    networks:
      - registry
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: mongo
      ALLOW_EMPTY_PASSWORD: yes
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    
  # mongo_createdb:
  #   links:
  #     - mongodb
  #   image: "bitnami/mongodb:3.4.10-r0"
  #   container_name: mongodb_createdb
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - registry
  #   environment:
  #     MONGODB_ROOT_PASSWORD: mongo
  #     ALLOW_EMPTY_PASSWORD: yes
  #   command: "sleep 60; /opt/bitnami/mongodb/bin/mongo -u root -p mongo --authenticationDatabase=admin --host mongodb < /app/create-dbs.json"
  #   volumes:
  #     - ./scripts:/app
  
  ######################################################################################################################################################
  # Enable the addusers block if you need to bootstrap the mongodb database
  ######################################################################################################################################################
  #init-database:
  #  build: ../init-database/
  #  container_name: init-database
  #  networks:
  #    - registry
  #  depends_on:
  #    - mongodb
  #  links:
  #    - mongodb
  ######################################################################################################################################################

  ######################################################################################################################################################
  # Enable the addusers block if you want to create users based on a txt file, each user must be in one line
  ######################################################################################################################################################
  addusers:
    build: ../addusers/
    container_name: addusers
    networks:
     - registry
    depends_on:
      - mongodb
    links:
      - mongodb
  ######################################################################################################################################################

  cassandra:
    image: "cassandra:3.11.19"
    container_name: cassandra
    ports:
     - "9042:9042"
     - "7000:7000"
    networks:
      - registry
    environment:
      CASSANDRA_STARTUP_CQL: "CREATE KEYSPACE registry WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
      CASSANDRA_CLUSTER_NAME: "registry"
      #CASSANDRA_USER: "registry" 
      #CASSANDRA_PASSWORD: "registry"
      CASSANDRA_DATACENTER: "datacenter1"
  
  mosquitto:
    #image: "konkerlabs/mosquitto:1.8.0"
    image: "eclipse-mosquitto:1.6.15"
    container_name: mosquitto
    ports:
     - "1883:1883"
    networks:
      - registry
    environment:
      MONGODB_URL: "mongodb://registry:registry@mongodb/registry?authSource=registry&minPoolSize=5"
      MONGODB_DATABASE: "registry"
      SUPERUSER_SUB_USERNAME: registry
      SUPERUSER_SUB_SECRET: "PBKDF2$sha256$1000000$oeks5948KfL1TpUbzrHqhw==$TbRvz1vP5OSBQk8clE5j8QWpoU+gEDBTRjYSfwjdHc4="
      SUPERUSER_PUB_USERNAME: registry
      SUPERUSER_PUB_SECRET: "PBKDF2$sha256$1000000$oeks5948KfL1TpUbzrHqhw==$TbRvz1vP5OSBQk8clE5j8QWpoU+gEDBTRjYSfwjdHc4="


  api:
    image: "konkerlabs/konker-registry:konker.registry.api-1454482032"
    #build: ../../../konker.registry.api/
    container_name: api
    links:
     - mongodb
     - cassandra
     - redis
     - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - registry
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      SWAGGER_HOSTNAME: "api-ucmp.soneca.dev"
      SWAGGER_PROTOCOL: "https"
      PUB_SERVER_SSL_ENABLED: "true"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_PORT: 27017
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"

      MONGO_AUDIT_HOSTNAME: mongodb
      MONGO_AUDIT_PORT: 27017
      MONGO_AUDIT_USERNAME: "registry"
      MONGO_AUDIT_PASSWORD: "registry"
      
      MONGO_BILLING_HOSTNAME: mongodb
      MONGO_BILLING_PORT: 27017
      MONGO_BILLING_USERNAME: "registry"
      MONGO_BILLING_PASSWORD: "registry"

      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_PORT: 27017
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_PORT: 27017
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"

      MONGO_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGO_PRIVATE_STORAGE_PORT: 27017
      MONGO_PRIVATE_STORAGE_USERNAME: "registry"
      MONGO_PRIVATE_STORAGE_PASSWORD: "registry"
      
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"
      MONGODB_PORT: 27017

      MONGO_HOSTNAME: mongodb
      MONGO_USERNAME: "registry"
      MONGO_PASSWORD: "registry"
      MONGO_PORT: 27017

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      RABBITMQ_API_PORT: "15672"
      RABBITMQ_API_USERNAME: "rabbitmq"
      RABBITMQ_API_PASSWORD: "rabbitmq"
      RABBITMQ_USERNAME: "rabbitmq"
      RABBITMQ_PASSWORD: "rabbitmq"
      RABBITMQ_VIRTUALHOST: "/"
      
      EVENT_STORAGE_BEAN: "cassandraEvents"
      CASSANDRA_CLUSTERNAME: "registry"
      CASSANDRA_DATACENTER: "datacenter1"
      CASSANDRA_KEYSPACE: "registry"
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
  data:
    image: "konkerlabs/konker-registry:konker.registry.data-1454482032"
    #build:  ../../../konker.registry.data/
    container_name: data
    links:
     - mongodb
     - cassandra
     - redis
     - rabbitmq
    ports:
      - "8181:8080"
    networks:
      - registry
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_PORT: 27017
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"

      MONGO_AUDIT_HOSTNAME: mongodb
      MONGO_AUDIT_PORT: 27017
      MONGO_AUDIT_USERNAME: "registry"
      MONGO_AUDIT_PASSWORD: "registry"
      
      MONGO_BILLING_HOSTNAME: mongodb
      MONGO_BILLING_PORT: 27017
      MONGO_BILLING_USERNAME: "registry"
      MONGO_BILLING_PASSWORD: "registry"

      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_PORT: 27017
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_PORT: 27017
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"

      MONGO_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGO_PRIVATE_STORAGE_PORT: 27017
      MONGO_PRIVATE_STORAGE_USERNAME: "registry"
      MONGO_PRIVATE_STORAGE_PASSWORD: "registry"
      
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"
      MONGODB_PORT: 27017

      MONGO_HOSTNAME: mongodb
      MONGO_USERNAME: "registry"
      MONGO_PASSWORD: "registry"
      MONGO_PORT: 27017

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      RABBITMQ_API_PORT: "15672"
      RABBITMQ_API_USERNAME: "rabbitmq"
      RABBITMQ_API_PASSWORD: "rabbitmq"
      RABBITMQ_USERNAME: "rabbitmq"
      RABBITMQ_PASSWORD: "rabbitmq"
      RABBITMQ_VIRTUALHOST: "/"
      
      EVENT_STORAGE_BEAN: "cassandraEvents"
      CASSANDRA_CLUSTERNAME: "registry"
      CASSANDRA_DATACENTER: "datacenter1"
      CASSANDRA_KEYSPACE: "registry"
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
  data-processor:
    image: "konkerlabs/konker-registry:konker.registry.data.processor-1454482032"
    #build:  ../../../konker.registry.data.processor/
    container_name: data-processor
    links:
      - mongodb
      - cassandra
      - redis
      - rabbitmq
    ports:
      - "8282:8080"
    networks:
      - registry
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_PORT: 27017
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"

      MONGO_AUDIT_HOSTNAME: mongodb
      MONGO_AUDIT_PORT: 27017
      MONGO_AUDIT_USERNAME: "registry"
      MONGO_AUDIT_PASSWORD: "registry"
      
      MONGO_BILLING_HOSTNAME: mongodb
      MONGO_BILLING_PORT: 27017
      MONGO_BILLING_USERNAME: "registry"
      MONGO_BILLING_PASSWORD: "registry"

      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_PORT: 27017
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_PORT: 27017
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"

      MONGO_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGO_PRIVATE_STORAGE_PORT: 27017
      MONGO_PRIVATE_STORAGE_USERNAME: "registry"
      MONGO_PRIVATE_STORAGE_PASSWORD: "registry"
      
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"
      MONGODB_PORT: 27017

      MONGO_HOSTNAME: mongodb
      MONGO_USERNAME: "registry"
      MONGO_PASSWORD: "registry"
      MONGO_PORT: 27017

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      RABBITMQ_API_PORT: "15672"
      RABBITMQ_API_USERNAME: "rabbitmq"
      RABBITMQ_API_PASSWORD: "rabbitmq"
      RABBITMQ_USERNAME: "rabbitmq"
      RABBITMQ_PASSWORD: "rabbitmq"
      RABBITMQ_VIRTUALHOST: "/"
      
      EVENT_STORAGE_BEAN: "cassandraEvents"
      CASSANDRA_CLUSTERNAME: "registry"
      CASSANDRA_DATACENTER: "datacenter1"
      CASSANDRA_KEYSPACE: "registry"
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
  bridge:
    #image: "konkerlabs/konker-platform:konker.mqtt.bridge-latest"
    image: "konkerlabs/konker-platform:registry-mqtt-bridge-latest"
    #build: ../../konker.registry.data.processor/
    container_name: bridge
    links:
      - mongodb
      - cassandra
      - redis
      - rabbitmq
    ports:
      - "8585:8080"
    networks:
      - registry
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_PORT: 27017
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"

      MONGO_AUDIT_HOSTNAME: mongodb
      MONGO_AUDIT_PORT: 27017
      MONGO_AUDIT_USERNAME: "registry"
      MONGO_AUDIT_PASSWORD: "registry"
      
      MONGO_BILLING_HOSTNAME: mongodb
      MONGO_BILLING_PORT: 27017
      MONGO_BILLING_USERNAME: "registry"
      MONGO_BILLING_PASSWORD: "registry"

      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_PORT: 27017
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_PORT: 27017
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"

      MONGO_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGO_PRIVATE_STORAGE_PORT: 27017
      MONGO_PRIVATE_STORAGE_USERNAME: "registry"
      MONGO_PRIVATE_STORAGE_PASSWORD: "registry"
      
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"
      MONGODB_PORT: 27017

      MONGO_HOSTNAME: mongodb
      MONGO_USERNAME: "registry"
      MONGO_PASSWORD: "registry"
      MONGO_PORT: 27017

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBIT_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      RABBITMQ_APIPORT: "5672"
      RABBITMQ_APIUSERNAME: "admin"
      RABBITMQ_APIPASSWORD: "rabbitmq"
      RABBIT_USERNAME: "admin"
      RABBIT_PASSWORD: "rabbitmq"
      RABBIT_DEVICE_CONTEXT: "/"
      MQTT_HOSTNAME: "tcp://mosquitto:1883"
      MQTT_SUB_USERNAME: "0jeOyWW4cpx5Bicx"
      MQTT_SUB_PASSWORD: "registry"
      MQTT_PUB_USERNAME: "xK7GeQO1Z8FtabkT"
      MQTT_PUB_PASSWORD: "registry"
      
      EVENT_STORAGE_BEAN: "cassandraEvents"
      CASSANDRA_CLUSTERNAME: "registry"
      CASSANDRA_DATACENTER: "datacenter1"
      CASSANDRA_KEYSPACE: "registry"
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"

  router:
    image: "konkerlabs/konker-registry:konker.registry.router-1454482032"
    #build: ../../../konker.registry.router/
    container_name: router
    links:
      - mongodb
      - cassandra
      - redis
      - rabbitmq
    ports:
      - "8383:8080"
    networks:
      - registry
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_PORT: 27017
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"

      MONGO_AUDIT_HOSTNAME: mongodb
      MONGO_AUDIT_PORT: 27017
      MONGO_AUDIT_USERNAME: "registry"
      MONGO_AUDIT_PASSWORD: "registry"
      
      MONGO_BILLING_HOSTNAME: mongodb
      MONGO_BILLING_PORT: 27017
      MONGO_BILLING_USERNAME: "registry"
      MONGO_BILLING_PASSWORD: "registry"

      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_PORT: 27017
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_PORT: 27017
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"

      MONGO_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGO_PRIVATE_STORAGE_PORT: 27017
      MONGO_PRIVATE_STORAGE_USERNAME: "registry"
      MONGO_PRIVATE_STORAGE_PASSWORD: "registry"
      
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"
      MONGODB_PORT: 27017

      MONGO_HOSTNAME: mongodb
      MONGO_USERNAME: "registry"
      MONGO_PASSWORD: "registry"
      MONGO_PORT: 27017

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      #RABBITMQ_APIPORT: "5672"
      RABBITMQ_APIUSERNAME: "user"
      RABBITMQ_APIPASSWORD: "bitnami"
      RABBITMQ_USERNAME: "rabbitmq"
      RABBITMQ_PASSWORD: "rabbitmq"
      RABBITMQ_VHOST: "/"
      
      EVENT_STORAGE_BEAN: "cassandraEvents"
      CASSANDRA_CLUSTERNAME: "registry"
      CASSANDRA_DATACENTER: "datacenter1"
      CASSANDRA_KEYSPACE: "registry"
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
  web:
    #image: "konkerlabs/konker-platform:konker.registry.web-latest"
    image: "konkerlabs/konker-registry:konker.registry.web-1454482032"
    #build: ../../../konker.registry.web/
    container_name: web
    links:
      - mongodb
      - cassandra
      - redis
      - rabbitmq
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8484:8080"
      - "8888:80"
    networks:
      - registry
    environment:
      PUB_SERVER_SSL_ENABLED: "true"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_PORT: 27017
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"

      MONGO_AUDIT_HOSTNAME: mongodb
      MONGO_AUDIT_PORT: 27017
      MONGO_AUDIT_USERNAME: "registry"
      MONGO_AUDIT_PASSWORD: "registry"
      
      MONGO_BILLING_HOSTNAME: mongodb
      MONGO_BILLING_PORT: 27017
      MONGO_BILLING_USERNAME: "registry"
      MONGO_BILLING_PASSWORD: "registry"

      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_PORT: 27017
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_PORT: 27017
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"

      MONGO_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGO_PRIVATE_STORAGE_PORT: 27017
      MONGO_PRIVATE_STORAGE_USERNAME: "registry"
      MONGO_PRIVATE_STORAGE_PASSWORD: "registry"
      
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"
      MONGODB_PORT: 27017

      MONGO_HOSTNAME: mongodb
      MONGO_USERNAME: "registry"
      MONGO_PASSWORD: "registry"
      MONGO_PORT: 27017

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      #RABBITMQ_APIPORT: "5672"
      RABBITMQ_APIUSERNAME: "user"
      RABBITMQ_APIPASSWORD: "bitnami"
      RABBITMQ_USERNAME: "rabbitmq"
      RABBITMQ_PASSWORD: "rabbitmq"
      RABBITMQ_VHOST: "/"
      
      EVENT_STORAGE_BEAN: "cassandraEvents"
      CASSANDRA_CLUSTERNAME: "registry"
      CASSANDRA_DATACENTER: "datacenter1"
      CASSANDRA_KEYSPACE: "registry"
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_PORT: 9042

      AMAZON_KINESISROUTEENABLED: "false"
      
      CDN_NAME: "user" 
      CDN_PREFIX: "https://s3.eu-central-1.amazonaws.com"
      CDN_KEY: "KEY"
      CDN_SECRET: "PASS"
      CDN_MAX-SIZE: "500000" 
      CDN_FILE-TYPES: "jpg,png,jpeg"
      CDN_ENABLED: "false"

      SMS_ENABLED: "false"

      SECURITY_LOGIN_PAGE: "/login"
      SECURITY_SUCCESS_LOGIN_URL: "/"

      PUB_HTTP_HOSTNAME: "data-ucmp.soneca.dev"
      PUBSERVER_HTTPPORT:  "80" 
      PUB_SERVER_HTTP_CTX:  "registry"
      PUBSERVER_HTTPSPORT: "443"
      PUB_MQTT_HOSTNAME: "ucmp.soneca.dev"
      PUB_SERVER_MQTT_PORT: "1883"
      PUB_SERVER_MQTT_TLS_PORT: "8883"

  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - registry
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/certs:ro
    depends_on:
      - web
      - api
      - data
    restart: unless-stopped
