{{- if .Values.configmap -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "konker-registry-api-helm.name" . }}
data:
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}