networks:
  registry:
    driver: bridge
services:
  rabbitmq:
    image: "bitnami/rabbitmq:3.7.3-r3"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - registry
  redis:
    image: "redis:4.0-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - registry
  mongodb:
    image: "bitnami/mongodb:3.4.10-r0"
    container_name: mongodb
    ports:
     - "27017:27017"
    networks:
      - registry
    environment:
      MONGODB_ROOT_PASSWORD: mongo
      ALLOW_EMPTY_PASSWORD: yes
      #MONGODB_ROOT_USER: mongo
      #MONGODB_USERNAME: registry
      #MONGODB_PASSWORD: registry
      #MONGODB_DATABASE: registry
      #MONGODB_EXTRA_DATABASES: "audit, registry"
      #MONGODB_EXTRA_USERNAMES: registry
  
  envblueprint:
    #image: "bitnami/mongodb:3.4.10-r0"
    build: ../../konker.scripts/env-blueprint/
    container_name: envblueprint
    networks:
      - registry
    links:
     - mongodb
    #environment:
      #MONGODB_ROOT_PASSWORD: mongo
      #ALLOW_EMPTY_PASSWORD: yes
      #MONGODB_ROOT_USER: mongo
      #MONGODB_USERNAME: registry
      #MONGODB_PASSWORD: registry
      #MONGODB_DATABASE: registry
      #MONGODB_EXTRA_DATABASES: "audit, registry"
      #MONGODB_EXTRA_USERNAMES: registry

  cassandra:
    image: "bitnami/cassandra:3.11.1-r3"
    container_name: cassandra
    ports:
     - "9042:9042"
     - "7000:7000"
    networks:
      - registry
    environment:
      CASSANDRA_STARTUP_CQL: "CREATE KEYSPACE registry WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
      CASSANDRA_CLUSTER_NAME: "registry"
      #CASSANDRA_USER: "registry" 
      #CASSANDRA_PASSWORD: "registry"
      CASSANDRA_DATACENTER: "datacenter1"
  
  mosquitto:
    image: "eclipse/mosquitto:1.4.8"
    container_name: mosquitto
    ports:
     - "1883:1883"
    networks:
      - registry
    #environment:
      # CASSANDRA_STARTUP_CQL: "CREATE KEYSPACE registry WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
      # CASSANDRA_CLUSTER_NAME: "registry"
      # #CASSANDRA_USER: "registry" 
      # #CASSANDRA_PASSWORD: "registry"
      # CASSANDRA_DATACENTER: "datacenter1"

  api:
    #image: "konkerlabs/konker-platform:konker.registry.api-5144526589"
    build: ../../konker.registry.api/
    container_name: api
    links:
     - mongodb
     - cassandra
     - redis
     - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - registry
    environment:
      #SWAGGER_HOSTNAME: "localhost:8080"
      #SWAGGER_PROTOCOL: "http"
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"
      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      RABBITMQ_API_PORT: "15672"
      RABBITMQ_API_USERNAME: "user"
      RABBITMQ_API_PASSWORD: "bitnami"
      RABBITMQ_USERNAME: "user"
      RABBITMQ_PASSWORD: "bitnami"
      RABBITMQ_VIRTUALHOST: "/"
      
      EVENT_STORAGE_BEAN: cassandra
      CASSANDRA_CLUSTERNAME: registry
      CASSANDRA_DATACENTER: registry
      CASSANDRA_KEYSPACE: registry
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
  data:
    #image: "konkerlabs/konker-platform:konker.registry.api-5144526589"
    build: ../../konker.registry.data/
    container_name: data
    links:
     - mongodb
     - cassandra
     - redis
     - rabbitmq
    ports:
      - "8181:8080"
    networks:
      - registry
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"
      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      RABBITMQ_API_PORT: "15672"
      RABBITMQ_API_USERNAME: "user"
      RABBITMQ_API_PASSWORD: "bitnami"
      RABBITMQ_USERNAME: "user"
      RABBITMQ_PASSWORD: "bitnami"
      RABBITMQ_VIRTUALHOST: "/"
      
      EVENT_STORAGE_BEAN: cassandra
      CASSANDRA_CLUSTERNAME: registry
      CASSANDRA_DATACENTER: registry
      CASSANDRA_KEYSPACE: registry
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
  data-processor:
    #image: "konkerlabs/konker-platform:konker.registry.api-5144526589"
    build: ../../konker.registry.data.processor/
    container_name: data-processor
    links:
      - mongodb
      - cassandra
      - redis
      - rabbitmq
    ports:
      - "8282:8080"
    networks:
      - registry
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"
      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      RABBITMQ_API_PORT: "15672"
      RABBITMQ_API_USERNAME: "user"
      RABBITMQ_API_PASSWORD: "bitnami"
      RABBITMQ_USERNAME: "user"
      RABBITMQ_PASSWORD: "bitnami"
      RABBITMQ_VIRTUALHOST: "/"
      
      EVENT_STORAGE_BEAN: cassandra
      CASSANDRA_CLUSTERNAME: registry
      CASSANDRA_DATACENTER: registry
      CASSANDRA_KEYSPACE: registry
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
  bridge:
    image: "konkerlabs/konker-platform:registry-mqtt-bridge-latest"
    #build: ../../konker.registry.data.processor/
    container_name: bridge
    links:
      - mongodb
      - cassandra
      - redis
      - rabbitmq
    ports:
      - "8585:8080"
    networks:
      - registry
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"
      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBIT_HOSTNAME: "rabbitmq"
      #RABBITMQ_API_HOST: "rabbitmq"
      #RABBITMQ_APIPORT: "5672"
      #RABBITMQ_APIUSERNAME: "user"
      #RABBITMQ_APIPASSWORD: "bitnami"
      RABBIT_USERNAME: "user"
      RABBIT_PASSWORD: "bitnami"
      RABBIT_DEVICE_CONTEXT: "/"
      MQTT_HOSTNAME: "tcp://mosquitto:1883"
      MQTT_SUB_USERNAME: "brige"
      MQTT_SUB_PASSWORD: "brigde"
      MQTT_PUB_USERNAME: "brigde"
      MQTT_PUB_PASSWORD: "bridge"
      
      EVENT_STORAGE_BEAN: cassandra
      CASSANDRA_CLUSTERNAME: registry
      CASSANDRA_DATACENTER: registry
      CASSANDRA_KEYSPACE: registry
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
  router:
    #image: "konkerlabs/konker-platform:konker.registry.api-5144526589"
    build: ../../konker.registry.router/
    container_name: router
    links:
      - mongodb
      - cassandra
      - redis
      - rabbitmq
    ports:
      - "8383:8080"
    networks:
      - registry
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"
      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      #RABBITMQ_APIPORT: "5672"
      RABBITMQ_APIUSERNAME: "user"
      RABBITMQ_APIPASSWORD: "bitnami"
      RABBITMQ_USERNAME: "user"
      RABBITMQ_PASSWORD: "bitnami"
      RABBITMQ_VHOST: "/"
      
      EVENT_STORAGE_BEAN: cassandra
      CASSANDRA_CLUSTERNAME: registry
      CASSANDRA_DATACENTER: registry
      CASSANDRA_KEYSPACE: registry
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
  web:
    #image: "konkerlabs/konker-platform:konker.registry.web-latest"
    build: ../../konker.registry.web/
    container_name: web
    links:
      - mongodb
      - cassandra
      - redis
      - rabbitmq
    ports:
      - "8484:8080"
    networks:
      - registry
    environment:
      PUB_SERVER_SSL_ENABLED: "false"

      MONGODB_AUDIT_HOSTNAME: mongodb
      MONGODB_AUDIT_USERNAME: "registry"
      MONGODB_AUDIT_PASSWORD: "registry"
      MONGODB_BILLING_HOSTNAME: mongodb
      MONGODB_BILLING_USERNAME: "registry"
      MONGODB_BILLING_PASSWORD: "registry"
      MONGODB_PRIVATE_STORAGE_HOSTNAME: "mongodb"
      MONGODB_PRIVATE_STORAGE_USERNAME: "registry"
      MONGODB_PRIVATE_STORAGE_PASSWORD: "registry"
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "registry"
      MONGODB_PASSWORD: "registry"

      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"

      RABBITMQ_HOSTNAME: "rabbitmq"
      RABBITMQ_API_HOST: "rabbitmq"
      #RABBITMQ_APIPORT: "5672"
      RABBITMQ_APIUSERNAME: "user"
      RABBITMQ_APIPASSWORD: "bitnami"
      RABBITMQ_USERNAME: "user"
      RABBITMQ_PASSWORD: "bitnami"
      RABBITMQ_VHOST: "/"
      
      EVENT_STORAGE_BEAN: cassandra
      CASSANDRA_CLUSTERNAME: registry
      CASSANDRA_DATACENTER: registry
      CASSANDRA_KEYSPACE: registry
      CASSANDRA_HOSTNAME: "cassandra"
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra

      AMAZON_KINESISROUTEENABLED: "false"
      
      CDN_NAME: "user" 
      CDN_PREFIX: "https://s3.eu-central-1.amazonaws.com"
      CDN_KEY: "KEY"
      CDN_SECRET: "PASS"
      CDN_MAX-SIZE: "500000" 
      CDN_FILE-TYPES: "jpg,png,jpeg"
      CDN_ENABLED: "false"

      SMS_ENABLED: "false"

      SECURITY_LOGIN_PAGE: "/login"
      SECURITY_SUCCESS_LOGIN_URL: "/"
