# API
server {
    listen 443 ssl;
    server_name api-ucmp.soneca.dev;

    ssl_certificate     /etc/nginx/certs/api/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/api/private.key;

    location / {
        proxy_pass http://172.18.0.1:8080;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";
    }
}

# Data
server {
    listen 443 ssl;
    server_name data-ucmp.soneca.dev;

    ssl_certificate     /etc/nginx/certs/data/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/data/private.key;

    location / {
        proxy_pass http://172.18.0.1:8181;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";
    }
}

# WEB
server {
    listen 443 ssl;
    server_name ucmp.soneca.dev default;

    ssl_certificate     /etc/nginx/certs/web/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/web/private.key;

    location / {
        proxy_pass http://172.18.0.1:8888;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name ucmp.soneca.dev;

    location / {
        proxy_pass http://172.18.0.1:8484;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}


server {
    listen 80;
    server_name data-ucmp.soneca.dev;

    location / {
        proxy_pass http://172.18.0.1:8181;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name api-ucmp.soneca.dev;

    location / {
        proxy_pass http://172.18.0.1:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}