{{- if .Values.configmap -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "konker-data.fullname" . }}
    labels:
      {{- include "konker-data.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}