{{- if .Values.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "konker-registry-router-helm.name" . }}
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}