{{- if .Values.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "konker-registry-data-helm.name" . }}
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}