{{- if .Values.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "konker-router.fullname" . }}
  labels:
    {{- include "konker-router.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}